# Generated by Django 5.0.2 on 2024-03-12 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('value', models.TextField(verbose_name='SMART值')),
                ('disk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base.disk', verbose_name='所属硬盘')),
            ],
        ),
    ]
