# Generated by Django 5.0.2 on 2024-03-12 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Disk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smart',
            name='failure',
            field=models.BooleanField(default=False, verbose_name='是否损坏'),
            preserve_default=False,
        ),
    ]
