# Generated by Django 5.0.2 on 2024-03-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory', models.IntegerField(verbose_name='Memory')),
                ('rankid', models.IntegerField(verbose_name='Rank ID')),
                ('bankid', models.IntegerField(verbose_name='Bank ID')),
                ('row', models.IntegerField(verbose_name='行')),
                ('col', models.IntegerField(verbose_name='列')),
                ('datetime', models.DateTimeField(verbose_name='产生时间')),
            ],
            options={
                'verbose_name': '内存日志',
                'verbose_name_plural': '内存日志',
            },
        ),
        migrations.CreateModel(
            name='PCIELog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_severity', models.CharField(max_length=64, verbose_name='Error Severity')),
                ('pcie_bus_error_type', models.CharField(max_length=64, verbose_name='PCIE Bus Error Type')),
                ('receiver_id', models.CharField(max_length=64, verbose_name='Receiver ID')),
                ('vendor_id', models.CharField(max_length=64, verbose_name='Vendor ID')),
                ('device_id', models.CharField(max_length=64, verbose_name='Device ID')),
                ('bus', models.CharField(max_length=64, verbose_name='Bus')),
                ('device', models.CharField(max_length=64, verbose_name='Device')),
                ('datetime', models.DateTimeField(verbose_name='产生时间')),
            ],
            options={
                'verbose_name': 'PCIE日志',
                'verbose_name_plural': 'PCIE日志',
            },
        ),
        migrations.CreateModel(
            name='ServerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('INFO', 'INFO'), ('WARNING', 'WARNING'), ('CRITICAL', 'CRITICAL'), ('ALERT', 'ALERT'), ('UNDEFINED', 'UNDEFINED')], max_length=16, verbose_name='故障等级')),
                ('type', models.CharField(choices=[('CPU', 'CPU'), ('PSU', 'PSU'), ('Memory', 'Memory'), ('Disk', 'Disk'), ('PCIE', 'PCIE'), ('FAN', 'FAN'), ('Other', 'Other')], max_length=16, verbose_name='故障类型')),
                ('code', models.CharField(default='AUGG0000', max_length=64, verbose_name='事件码')),
                ('datetime', models.DateTimeField(verbose_name='产生时间')),
                ('message', models.TextField(verbose_name='日志信息')),
            ],
            options={
                'verbose_name': '服务器日志',
                'verbose_name_plural': '服务器日志',
            },
        ),
    ]
