# Generated by Django 5.0.2 on 2024-03-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcielog',
            name='function',
            field=models.CharField(default='', max_length=64, verbose_name='Device'),
            preserve_default=False,
        ),
    ]
